CREATE TABLE emp_expr(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT'ID，主键',
	BEGIN DATE COMMENT '开始时间',
	END DATE COMMENT '结束时间',
	company VARCHAR(50) COMMENT'公司名称',
	job VARCHAR(50) COMMENT'职位',
	emp_id INT UNSIGNED COMMENT'关联id'
)COMMENT '工作经历表';